'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon
    dir
    vcs
    status
    command_execution_time
    background_jobs
    direnv
    asdf
    virtualenv
    anaconda
    pyenv
    goenv
    nodenv
    nvm
    nodeenv
    node_version
    go_version
    rust_version
    dotnet_version
    php_version
    laravel_version
    java_version
    package
    rbenv
    rvm
    fvm
    luaenv
    jenv
    plenv
    perlbrew
    phpenv
    scalaenv
    haskell_stack
    kubecontext
    terraform
    terraform_version
    aws
    aws_eb_env
    azure
    gcloud
    google_app_cred
    toolbox
    context
    nordvpn
    ranger
    nnn
    lf
    xplr
    vim_shell
    midnight_commander
    nix_shell
    chezmoi_shell
    vpn_ip
    load
    disk_usage
    ram
    swap
    todo
    timewarrior
    taskwarrior
    per_directory_history
    cpu_arch
    time
    ip
    public_ip
    proxy
    battery
    wifi
    example
    newline
    prompt_char
  )

  typeset -g POWERLEVEL9K_MODE=nerdfont-v3
  typeset -g POWERLEVEL9K_ICON_PADDING=none

  typeset -g POWERLEVEL9K_BACKGROUND=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=

  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=true

  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=7
    typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' '
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=' '
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
  fi

  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=

  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=2
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=1

  typeset -g POWERLEVEL9K_DIR_FOREGROUND=4
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=4
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=4

  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=2
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=3

  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=1
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=1

  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=3

  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=1

  typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=3

  typeset -g POWERLEVEL9K_ASDF_FOREGROUND=6

  typeset -g POWERLEVEL9K_ASDF_RUBY_FOREGROUND=1

  typeset -g POWERLEVEL9K_ASDF_PYTHON_FOREGROUND=6

  typeset -g POWERLEVEL9K_ASDF_GOLANG_FOREGROUND=6

  typeset -g POWERLEVEL9K_ASDF_NODEJS_FOREGROUND=2

  typeset -g POWERLEVEL9K_ASDF_RUST_FOREGROUND=4

  typeset -g POWERLEVEL9K_ASDF_DOTNET_CORE_FOREGROUND=5

  typeset -g POWERLEVEL9K_ASDF_FLUTTER_FOREGROUND=4

  typeset -g POWERLEVEL9K_ASDF_LUA_FOREGROUND=4

  typeset -g POWERLEVEL9K_ASDF_JAVA_FOREGROUND=4

  typeset -g POWERLEVEL9K_ASDF_PERL_FOREGROUND=6

  typeset -g POWERLEVEL9K_ASDF_ERLANG_FOREGROUND=1

  typeset -g POWERLEVEL9K_ASDF_ELIXIR_FOREGROUND=5

  typeset -g POWERLEVEL9K_ASDF_POSTGRES_FOREGROUND=6

  typeset -g POWERLEVEL9K_ASDF_PHP_FOREGROUND=5

  typeset -g POWERLEVEL9K_ASDF_HASKELL_FOREGROUND=3

  typeset -g POWERLEVEL9K_ASDF_JULIA_FOREGROUND=2

  typeset -g POWERLEVEL9K_NORDVPN_FOREGROUND=6

  typeset -g POWERLEVEL9K_RANGER_FOREGROUND=3

  typeset -g POWERLEVEL9K_NNN_FOREGROUND=3

  typeset -g POWERLEVEL9K_LF_FOREGROUND=3

  typeset -g POWERLEVEL9K_XPLR_FOREGROUND=3

  typeset -g POWERLEVEL9K_VIM_SHELL_FOREGROUND=3

  typeset -g POWERLEVEL9K_MIDNIGHT_COMMANDER_FOREGROUND=3

  typeset -g POWERLEVEL9K_NIX_SHELL_FOREGROUND=4

  typeset -g POWERLEVEL9K_CHEZMOI_SHELL_FOREGROUND=4

  typeset -g POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND=2
  typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND=3
  typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND=1

  typeset -g POWERLEVEL9K_RAM_FOREGROUND=2

  typeset -g POWERLEVEL9K_SWAP_FOREGROUND=3

  typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND=2
  typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND=3
  typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND=1

  typeset -g POWERLEVEL9K_TODO_FOREGROUND=4

  typeset -g POWERLEVEL9K_TIMEWARRIOR_FOREGROUND=4

  typeset -g POWERLEVEL9K_TASKWARRIOR_FOREGROUND=6

  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_FOREGROUND=5
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_FOREGROUND=3

  typeset -g POWERLEVEL9K_CPU_ARCH_FOREGROUND=3

  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=1
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=7
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=7

  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=6

  typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=6

  typeset -g POWERLEVEL9K_PYENV_FOREGROUND=6

  typeset -g POWERLEVEL9K_GOENV_FOREGROUND=6

  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=2

  typeset -g POWERLEVEL9K_NVM_FOREGROUND=2

  typeset -g POWERLEVEL9K_NODEENV_FOREGROUND=2

  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=2

  typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=6

  typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=4

  typeset -g POWERLEVEL9K_DOTNET_VERSION_FOREGROUND=5

  typeset -g POWERLEVEL9K_PHP_VERSION_FOREGROUND=5

  typeset -g POWERLEVEL9K_LARAVEL_VERSION_FOREGROUND=1

  typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND=4

  typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=6

  typeset -g POWERLEVEL9K_RBENV_FOREGROUND=1

  typeset -g POWERLEVEL9K_RVM_FOREGROUND=1

  typeset -g POWERLEVEL9K_FVM_FOREGROUND=4

  typeset -g POWERLEVEL9K_LUAENV_FOREGROUND=4

  typeset -g POWERLEVEL9K_JENV_FOREGROUND=4

  typeset -g POWERLEVEL9K_PLENV_FOREGROUND=6

  typeset -g POWERLEVEL9K_PERLBREW_FOREGROUND=67

  typeset -g POWERLEVEL9K_PHPENV_FOREGROUND=5

  typeset -g POWERLEVEL9K_SCALAENV_FOREGROUND=1

  typeset -g POWERLEVEL9K_HASKELL_STACK_FOREGROUND=3

  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=5

  typeset -g POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND=4

  typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND=4

  typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=3

  typeset -g POWERLEVEL9K_AWS_EB_ENV_FOREGROUND=2

  typeset -g POWERLEVEL9K_AZURE_OTHER_FOREGROUND=4

  typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=4

  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND=5

  typeset -g POWERLEVEL9K_TOOLBOX_FOREGROUND=3

  typeset -g POWERLEVEL9K_PUBLIC_IP_FOREGROUND=6

  typeset -g POWERLEVEL9K_VPN_IP_FOREGROUND=3

  typeset -g POWERLEVEL9K_IP_FOREGROUND=4

  typeset -g POWERLEVEL9K_PROXY_FOREGROUND=2

  typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=1

  typeset -g POWERLEVEL9K_BATTERY_{CHARGING,CHARGED}_FOREGROUND=2

  typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=3

  typeset -g POWERLEVEL9K_WIFI_FOREGROUND=4

  typeset -g POWERLEVEL9K_TIME_FOREGROUND=6

  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}

typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
