theme = "catppuccin_mocha"

[editor]
scrolloff = 8
line-number = "relative"
auto-format = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false
